# Generated by Django 4.2.6 on 2023-10-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('url', models.CharField(max_length=150, verbose_name='URL')),
                ('slug', models.CharField(max_length=100, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Site',
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('slug', models.CharField(max_length=100, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Ativo',
            },
        ),
        migrations.CreateModel(
            name='AssetsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('slug', models.CharField(max_length=100, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Tipo de ativo',
            },
        ),
        migrations.AlterModelOptions(
            name='importfile',
            options={'verbose_name': 'Arquivo'},
        ),
        migrations.CreateModel(
            name='EndPointConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100, verbose_name='Endpoint')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apiconnections', verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Endpoint',
            },
        ),
    ]
