# Generated by Django 4.2.6 on 2023-10-23 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apiconnections_assets_assetstype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.assetstype', verbose_name='Tipo de Ativo'),
        ),
    ]
